steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:latest',
        '-t', 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:${SHORT_SHA}',
        '.'
      ]
    dir: 'backend/services/rag-query-service'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:${SHORT_SHA}']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
        'run', 'deploy', 'rag-query-service',
        '--image', 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:latest',
        '--region', '${_GCP_REGION}',
        '--platform', 'managed',
        '--quiet'
      ]

images:
  - 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:latest'
  - 'us-east1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO_ID}/rag-query-service:${SHORT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY