version: "3.8"
services:
  # API Service
  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    volumes:
      - ./api-service:/app # Mount for live reload, ensure Dockerfile WORKDIR is /app for this
    # If you created a .env file, you can specify it here:
    # env_file:
    #   - ./services/api-service/.env 
    restart: always
