version: "3.8"
services:
  api-service:
    build:
      context: ./services/api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./services/api-service:/app # For Go, WORKDIR in Dockerfile is /app for dev builds
    # env_file:
    #   - ./services/api-service/.env 
    restart: always

  python-worker-service:
    build:
      context: ./services/python-worker-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
    volumes:
      - ./services/python-worker-service:/app 
    # env_file:
    #   - ./services/python-worker-service/.env 
    restart: always