version: "2.3"
services:
  server:
    build: ./server
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./server:/app
    restart: always
    ports:
      - 8000:8000
